---
- hosts: aws
  become: true
  tasks:
    - name: Install Docker
      dnf:
        name: docker
        state: present
        update_cache: yes
    - name: Delete Existing Container
      ignore_errors: true
      shell: |
        docker stop {{ CONTAINER_NAME }} && docker rm {{ CONTAINER_NAME }}
    - name: Deploy Application
      shell: |
        docker pull {{ REGISTRY_IMAGE }}
        docker run -d -p 8080:8080 --name {{ CONTAINER_NAME }} {{ REGISTRY_IMAGE }}